export const ALL_TABLE_REQUEST = "ALL_TABLE_REQUEST";
export const ALL_TABLE_SUCCESS = "ALL_TABLE_SUCCESS";
export const ALL_TABLE_FAIL = "ALL_TABLE_FAIL";

export const ADMIN_TABLE_REQUEST = "ADMIN_TABLE_REQUEST";
export const ADMIN_TABLE_SUCCESS = "ADMIN_TABLE_SUCCESS";
export const ADMIN_TABLE_FAIL = "ADMIN_TABLE_FAIL";

export const NEW_TABLE_REQUEST = "NEW_TABLE_REQUEST";
export const NEW_TABLE_SUCCESS = "NEW_TABLE_SUCCESS";
export const NEW_TABLE_RESET = "NEW_TABLE_RESET";
export const NEW_TABLE_FAIL = "NEW_TABLE_FAIL";

export const UPDATE_TABLE_REQUEST = "UPDATE_TABLE_REQUEST";
export const UPDATE_TABLE_SUCCESS = "UPDATE_TABLE_SUCCESS";
export const UPDATE_TABLE_RESET = "UPDATE_TABLE_RESET";
export const UPDATE_TABLE_FAIL = "UPDATE_TABLE_FAIL";

export const DELETE_TABLE_REQUEST = "DELETE_TABLE_REQUEST";
export const DELETE_TABLE_SUCCESS = "DELETE_TABLE_SUCCESS";
export const DELETE_TABLE_RESET = "DELETE_TABLE_RESET";
export const DELETE_TABLE_FAIL = "DELETE_TABLE_FAIL";

export const TABLE_DETAILS_REQUEST = "TABLE_DETAILS_REQUEST";
export const TABLE_DETAILS_SUCCESS = "TABLE_DETAILS_SUCCESS";
export const TABLE_DETAILS_FAIL = "TABLE_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";